### ISSUE TITLE
Only getting DIR:false after collate of SPLIT-seq

### ISSUE THREAD

**Issue by davidaknowles** [COMBINE-lab/alevin-fry#111]
Hi - I'm trying to run alevin-fry on the 150k mouse SPLIT-seq data from the original SPLIT-seq paper, roughly following the tutorial here: https://combine-lab.github.io/alevin-fry-tutorials/2022/split-seq/ (but of course with a mouse only index). My current issue is that after I run `generate-permit-list` and `collate` I get a collated rad file that _only_ contains DIR:false (i.e. antisense) alignments, whereas before collation I see a mix (and actually about 2x DIR:true i.e. sense). Is this expected?

**Comment by rob-p** [comment]
Hi @davidaknowles,

  Thanks for filing the issue / raising this question.  This is an effect of how the `collate` command works that, admittedly, is not well documented (we'll aim to fix that).

  Basically, during collate, `alevin-fry` also filters out mappings that were not consistent with the required orientation specification.  Since, in the filtered and collated RAD file, it is assumed that all reads have a "consistent" orientation, that information is no longer actively tracked, and the RAD file just marks the orientation of each mapping as `FALSE`.  This behavior is somewhat of a historical artifact, but it's how the collate command currently works — since that information will no longer participate in quantification.  If there is a good reason that one needs to retain that orientation information, however, we can work on supporting that and propagating the orientation to the collated RAD file.

Best,
Rob

**Comment by davidaknowles** [comment]
Thanks for the rapid response! I think I can safely ignore orientation then.
