### ISSUE TITLE
Cannot get output

### ISSUE THREAD

**Issue by wangjiawen2013** [COMBINE-lab/alevin-fry#129]
Hello

I tried to reproduce the process according to the documentation in https://combine-lab.github.io/alevin-fry-tutorials/2023/simpleaf-piscem/

It displayed everything is fine:
![image](https://github.com/COMBINE-lab/alevin-fry/assets/29703450/96354947-7197-4074-9d1c-71498250aa52)

However, there is no data in the output:
![image](https://github.com/COMBINE-lab/alevin-fry/assets/29703450/1cdf5e1c-d168-4b2e-8f62-aeb4aa4f3f27)

And /simpleaf/plist/10x_v3_permit.txt is an empty file. 

What's wrong with it ? I nearly copied the whole code on the tutorial !

**Comment by rob-p** [comment]
Hi @wangjiawen2013,

  Thanks for sharing your report here.  I'm tagging @DongzeHE as he will be able to help as well. I can see that you're using `simpleaf` to run `alevin-fry` and to do the mapping etc.  Can show the result of doing `ls -la pbmc1k_quant/af_map`?
  
  I suspect the issue may be related to the `10x_v3_permit.txt` being empty — that's certainly not right. Since it's hosted on "Box", that link sometimes misbehaves, we will check it.

--Rob

**Comment by wangjiawen2013** [comment]
![image](https://github.com/COMBINE-lab/alevin-fry/assets/29703450/661dd09c-141b-4bc9-9ce3-7cb85e9a675c)

**Comment by wangjiawen2013** [comment]
It worked with the new permit list
