### ISSUE TITLE
How to realize umi-tools directional algorithm in alevin-fry

### ISSUE THREAD

**Issue by tengdiyouying608** [COMBINE-lab/alevin-fry#137]
Hi Alevin-fry developers,

I used to use UMI-tools, but now I want to switch to SimpleAF to significantly reduce processing time. How can I configure the parameters in SimpleAF to implement the “directional” method used in UMI-tools?

**Comment by rob-p** [comment]
Hi @tengdiyouying608,

  The original directional algorithm of UMI-tools isn't implemented in `alevin-fry`.  Rather, we implement the improved (but conceptually-related) version of this algorithm presented in the original [alevin](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1670-y) paper, which is co-authored with the authors of UMI-tools.  Specifically, rather than doing a greedy directional collapse, the new algorithm attempts to cover the graph using a minimal number of "arboresences" (directed trees), each of which can be explained by a single molecule.  This method is obtainable in alevin-fry by asking for the `parsimony` resolution mode.  If there is a specific reason you're interested in the directional algorithm itself though, or a use case where you think it is clearly most appropriate, @DongzeHE and I would be happy to discuss!

Best,
Rob

**Comment by tengdiyouying608** [comment]
Hi @rob-p ，
Thank you for your prompt response. In my data, I have tested with the 'parsimony' parameter and compared it with the 'unique' (left) and 'directional' (right) parameters in UMI-tools. The x-axis represents gene expression obtained through UMI-tools, and the y-axis represents gene expression obtained through 'parsimony'. It seems that the results from 'parsimony' are closer to UMI-tools' 'unique' which is essentially the uncorrected output. So, that's why I'm attempting to realize 'directional' in alevin-fry.  And when the values exceeds 1200,the differences between the two become more pronounced. If there are any details or information I might have overlooked, I would greatly appreciate it if you could let me know!
![1709603945126](https://github.com/COMBINE-lab/alevin-fry/assets/38912489/a01ad649-c718-4024-a5ef-cf27d8a829f5)

Best,
Margarita

**Comment by rob-p** [comment]
Hi Margarita (@tengdiyouying608),

  Very interesting!  This is certainly something worth understanding better.  Could you say a little bit about what type of data this is?  Is this data that you can share for testing purposes (we can of course do this offline e.g. via e-mail if that would be better).  @DongzeHE and I would be happy to take a look.  I wouldn't generally expect so large a difference, but seeing it, I might also worry if there's over-collapse under the UMI-tools model (that doesn't afaik, have the same constraint that there must be a transcript capable of supporting all of the collapsed UMIs).  Either way, we'd be happy to look more if the data, or a reproducible part of it, is sharable.

Best,
Rob

**Comment by wangjiawen2013** [comment]
Instead of  over-collapse under the UMI-tools model, I am worring about the **under-collapse** of alevin-fry ! Because I found the  result of umi-tools is more consistent with bulk RNAseq.

**Comment by tengdiyouying608** [comment]
Hi @rob-p ,

Could you provide me with an email address? I would like to sent you the data.

Best,
Margarita.
