### ISSUE TITLE
Generate splici; error in R script

### ISSUE THREAD

**Issue by ollieeknight** [COMBINE-lab/alevin-fry#26]
Heya,

I've been trying to generate the splici index using the R function given in your tutorial (https://combine-lab.github.io/alevin-fry-tutorials/2021/improving-txome-specificity/)

Unfortunately, after displaying "extracting introns using the separate approach", I receive a given error of "Error in (function (x : attempt to apply a non-function"

It then proceeds to writing outs, but I want to make sure everything is alright after this. Do you have any guidance?

Thanks a million

Ollie

**Comment by rob-p** [comment]
Hi @ollieeknight — Yes, this is a known (noise) issue in the R code.  It is expected and should _not_ affect the correctness of the output.  I'm tagging @DongzeHE and @csoneson here who can likely provide a more detailed description of why this message is output.  We'll try to address this noise in the future (or at least mention that it is expected behavior in the documentation).
