### ISSUE TITLE
No "usa_mode" flag

### ISSUE THREAD

**Issue by ZhuZhuoHSPH** [COMBINE-lab/alevin-fry#32]
Hello~ I'm following the RNA-velocity tutorial using alevin-fry. Everything works fine without any error but I don't have the `usa_mode` flag in the `meta_info.json` file. The `num_genes` is strange too, as I only have about 35k. I wonder what could be the cause. I'm using salmon 1.6.0 and alevin-fry 0.1.0 and working on human data. Thank you for your time.

**Comment by rob-p** [comment]
Hi @ZhuZhuoHSPH,

  Thanks for testing out `alevin-fry`!  The issue is that the version of `alevin-fry` you are using is too old, and pre-dates the existence of `usa_mode`.  I'd recommend upgrading to the latest version of `alevin-fry`, which you can either build from source, obtain from bioconda, or find in [this docker image](https://hub.docker.com/r/combinelab/usefulaf).

  If you have any trouble using the newest version, or if you still don't see what you expect in the output, please feel free to re-open this issue or to open a new one.

Best,
Rob

**Comment by ZhuZhuoHSPH** [comment]
Thank you Rob! I assumed conda installed the latest version and didn't realize the version I used is so outdated. I updated it to 0.4.3 and the output looks fine.
