### ISSUE TITLE
singularity running error

### ISSUE THREAD

**Issue by jjjscuedu** [COMBINE-lab/alevin-fry#44]
Dear all,

I have install alevin-fry and singularity by conda.

```
conda install alevin-fry
conda install -c conda-forge singularity
wget -v -O usefulaf.sif https://umd.box.com/shared/static/bcd8io9fbjc321pfgcomues5oe2a12cz
```

However, when I try to run simpleaf, there is still some errors like:

```
singularity exec --cleanenv --bind  /gpfs03/home/jingjing/project/test/alevin-fry/output/ usefulaf.sif ./simpleaf index -f \ human_CR_3.0/fasta/genome.fa -g human_CR_3.0/genes/genes.gtf -l 91 -t 40 -o output/human_CR_3.0_splici

ERROR  : Failed invoking the NEWUSER namespace runtime: Invalid argument
ABORT  : Retval = 255
```

I am newer to singularity, can anyone give me some suggestions for this error.

Thanks a lot!

Jingjing

**Comment by rob-p** [comment]
Hi @jjjscuedu,

I think your command is close, but not quite right, which is leading to the error.  Try the following (making sure that `/gpfs03/home/jingjing/project/test/alevin-fry/output` has already been created by you), which is taken from [here](https://github.com/COMBINE-lab/alevin-fry#building-the-splici-reference-and-index):

```
singularity exec --cleanenv --bind /gpfs03/home/jingjing/project/test/alevin-fry/output:/workdir --pwd /usefulaf/bash usefulaf.sif ./simpleaf index -f human_CR_3.0/fasta/genome.fa -g human_CR_3.0/genes/genes.gtf -l 91 -t 40 -o /workdir/human_CR_3.0_splici
```

Note the difference in `--bind`, it provides a mapping from a source location outside of the singularity image, to a location `/workdir` within the singularity image.  Also, note the use of `--pwd /usefulaf/bash` which tells singularity to execute the command from within the working directory `/usefulaf/bash`, which is required to run the `simpleaf` script.  Finally, note that the `-o` option takes a reference to the path `/workdir/human_CR_3.0_splici`.  This command _should_ work for you. Please let us know if you have any issues with it.

Best,
Rob

**Comment by jjjscuedu** [comment]
> Hi @jjjscuedu,
> 
> I think your command is close, but not quite right, which is leading to the error. Try the following (making sure that `/gpfs03/home/jingjing/project/test/alevin-fry/output` has already been created by you), which is taken from [here](https://github.com/COMBINE-lab/alevin-fry#building-the-splici-reference-and-index):
> 
> ```
> singularity exec --cleanenv --bind /gpfs03/home/jingjing/project/test/alevin-fry/output:/workdir --pwd /usefulaf/bash usefulaf.sif ./simpleaf index -f human_CR_3.0/fasta/genome.fa -g human_CR_3.0/genes/genes.gtf -l 91 -t 40 -o /workdir/human_CR_3.0_splici
> ```
> 
> Note the difference in `--bind`, it provides a mapping from a source location outside of the singularity image, to a location `/workdir` within the singularity image. Also, note the use of `--pwd /usefulaf/bash` which tells singularity to execute the command from within the working directory `/usefulaf/bash`, which is required to run the `simpleaf` script. Finally, note that the `-o` option takes a reference to the path `/workdir/human_CR_3.0_splici`. This command _should_ work for you. Please let us know if you have any issues with it.
> 
> Best, Rob

Dear Bob,

Thanks for your kindly reply.

I am still confused about the singularity usage.

According to your suggestions:

singularity exec --cleanenv --bind /gpfs03/home/jingjing/project/test/alevin-fry/output:/workdir --pwd /usefulaf/bash usefulaf.sif ./simpleaf index -f human_CR_3.0/fasta/genome.fa -g human_CR_3.0/genes/genes.gtf -l 91 -t 40 -o /workdir/human_CR_3.0_splici

My current working directory is:

/gpfs03/home/jingjing/project/test/alevin-fry/

[jingjing@headnode alevin-fry]$ ls -lh
total 1.5G
drwxrwxr-x 3 jingjing jingjing 4.0K Mar 28 10:03 data
drwxrwxr-x 4 jingjing jingjing 4.0K Mar 27 14:56 human_CR_3.0
drwxrwxr-x 2 jingjing jingjing 4.0K Mar 28 15:11 output
-rwxr--r-- 1 jingjing jingjing 1.5G Mar 28 13:51 usefulaf.sif
[jingjing@headnode alevin-fry]$ pwd
/gpfs03/home/jingjing/project/test/alevin-fry


The test dataset and usefulaf.sif is also under this folder.


I am still confuse for the --bind:  it provides a mapping from a source location outside of the singularity image. "source location" means what? the location for the singularity? I install singularity by conda.

Another parameter is: `--pwd /usefulaf/bash` which tells singularity to execute the command from within the working directory `/usefulaf/bash`.  I am not sure how to set this working directory.  "usefulaf.sif" is already under my current working directory. 


singularity exec --cleanenv --bind /gpfs03/home/jingjing/project/test/alevin-fry/output:/workdir --pwd /usefulaf/bash usefulaf.sif ./simpleaf index -f human_CR_3.0/fasta/genome.fa -g human_CR_3.0/genes/genes.gtf -l 91 -t 40 -o human_CR_3.0_splici


Thanks a lot!

Jingjing

**Comment by rob-p** [comment]
Hi @jjjscuedu,

  Sure, let me try to further describe these two command line options.  First `--bind`.  The `--bind` option takes arguments of the form:

```
--bind <source>:<target>
```

where `<source>` corresponds to an **absolute** path to some directory in your current environment — i.e. the environment from which are you invoking singularity, and `<target>` refers to some path **inside** of the singularity image.  In other words, when the singularity image is executed, it doesn't see the environment or local filesystem in the place where it was executed from — this is part of how the containerization provides a clean separation between the host environment and thec container.  The only data it can see is that that is mapped into some directory **within** the singularity image when it is executed.  This is done with the `--bind` option.  So the proposed option would say to the singularity execution, when I execute this image, map whatever is in the folder `/gpfs03/home/jingjing/project/test/alevin-fry/output` in the current environment to the folder `/workdir` within the singularity image.


Second, the `--pwd` option.  The `--pwd` option sets the *working directory* within the singularity image from which the subsequent command you pass will be executed.  The option `--pwd /usefulaf/bash` says, start the singularity image, and set the working directory in the image to be the folder `/usefulaf/bash`.  Again, this folder exists *inside* of the image (it is not referring to a path in the environment form which you are executing the image.  This is necessary since (as documented in the `usefulaf` readme) the `simpleaf` wrapper must be run from within the `bash` subdirectory — so this part of the invocation says to set the working directory in the image as such.

Best,
Rob

**Comment by rob-p** [comment]
Hi @jjjscuedu,

  Is the revised command working for you?  Are you able to run the tool through the singularity container?

--Rob

**Comment by rob-p** [comment]
I will assume things are working as expected now, but feel free to ping back here or open a new issue if they are not.
