### ISSUE TITLE
read length on the splici index

### ISSUE THREAD

**Issue by Aintzane99** [COMBINE-lab/alevin-fry#51]
Hello,

I tried to map some reads with variable lengths and obtained this output: 
'processed 277 Million fragments
hits: 0, hits per frag:  0
Found 277568862 reads with `N` in the UMI sequence and ignored the reads.
Please report on github if this number is too large'

I was wondering if the read length I specified when building the splici index had something to do with the fact that none of the reads mapped. I originally constructed that index in order to map a different set of files, specifiying the length that those previous sequences had (and the mapping went fine), which does not match with the length of the reads of the current files I'm trying to map. Besides, the current files have variable read lengths. Do you think the read length parameter could be the problem here? Should I build a different index for the files I'm trying to map now? But again, they have reads of different lengths. 

Thanks in advance,

Aintzane

**Comment by rob-p** [comment]
Hi @Aintzane99,

  No, I do not think this is the issue.  The effect of the read length parameter on the splici index construction generally has a very small effect on the mapping.  This message suggests that the problem is that in all reads that were processed, the UMI sequence contained invalid/indeterminate nucleotides (i.e. `N`) and so the read was discarded.  Are you sure that you've specified the barcode and UMI geometry correctly?  Can you share a small subset of the reads that don't map? We should inspect them manually to see if the barcode and UMI are showing up at the expected positions.

Best,
Rob

**Comment by Aintzane99** [comment]
Hi Rob,

The reads were obtained with the x10Chromium V3 protocol, which is composed  of a 16-bp cell barcode and 12-bp UMI in the Read1 file. I specified those parameters like this: 

$ salmon alevin -i .../grch38_splici_idx -p 10 -l IU --rad -1 R1_client.paired.fq.gz -2 R2_client.paired.tr.fq.gz  --bc-geometry 1[1-16] --umi-geometry 1[17-29] --read-geometry 2[1-end] -o client_pbmc_10k_v3_map --tgMap 2g.tsv

Regarding the unmapped reads, I understand you are referring to the ones in the ' unmapped_bc_count.bin' file. I tried to read the content of the binary file with several commands but none of them worked.

Thank you for your quick response,

Aintzane

**Comment by rob-p** [comment]
Hi @Aintzane99,

  Do you get any different behavior if you use the `--chromiumV3` flag instead of the custom geometry `--bc-geometry 1[1-16] --umi-geometry 1[17-29] --read-geometry 2[1-end]`?  Also, while the unmapped_bc_count.bin file may be interesting too, I was actually curious about the, say, first few hundred reads in `R1_client.paired.fq.gz` and `R2_client.paired.tr.fq.gz`.

Best,
Rob

**Comment by rob-p** [comment]
Have you had a chance to try this out @Aintzane99?

**Comment by Aintzane99** [comment]
Hello Rob,

Sorry, I had to solve some problems with the annotation file and couldn't
try it yet. Also I am waiting to trimm the read files (more specifically I
apply a trimming algorithm to the R2 files and then remove the reads that
didn't pass the quality check from the R1 file to match those of the R2
trimmed file). I will run the mapping command again whenever I have those
files ready with the chromiumV3 flag and let you know.

Thank you,

Aintzane
