### ISSUE TITLE
Refresh documentation for alevin-fry ecosystem

### ISSUE THREAD

**Issue by wmacnair** [COMBINE-lab/alevin-fry#53]
Hi

I've been using `alevin-fry` and friends to do my first ever mapping of FASTQ files, and I'm really appreciating the speed of the package, and the functionality for handling spliced + unspliced reads very naturally.

However I'm finding myself frustrated by the documentation. Some observations / questions / frustrations:

- The tutorials for the `alevin-fry` package do not refer to various useful additional packages. The only references to `alevinQC` and `usefulaf` in the `alevin-fry` codebase are in the README. (I only discovered them just now, so having followed the tutorial I think I have to rerun my pipeline adding --dumpFeatures to the `salmon alevin` step.)
- The tutorials are currently in the form of blog posts, which makes it hard for users to know which is most relevant to them. 
- I think that some of the tutorials are not up-to-date (e.g. referring to a roll-your-own loadFry function, instead of the one implemented in `fishpond` and / or `usefulaf`).
- I would find it useful to have something like a landing page, with a diagram showing all the relevant packages, their functionalities and how they interact.
- One absolutely essential task is loading the counts matrices into either `sce` or `anndata` objects, and this currently feels suboptimal. Both `usefulaf` and `fishpond` have quite a bit of other functionality, and `usefulaf` has a cool but non-obvious name. I wonder if something like an `AlevinToSCE` package which includes some of the `AlevinQC` functionality could be an option? `[sce import package]` could include: create an `sce` object from expected outputs; perhaps allow the `sce` creation function to have different options, e.g. knee / all / min bcs (I don't know how that would fit with the rest of the pipeline); allow me to view knee plots (I know that `alevin-fry` has the -knee option, but I will almost always want to check this myself); extract the profile of the empty droplets.

I'm a pretty experienced user of R packages for single cell analysis, trying out mapping for the first time with `alevin-fry`. It could well be that I've misunderstood something here, or missed some functionality, in which consider that as feedback about documentation :) I've been able to find most things, but I think finding your way around could definitely be made easier. 

I appreciate that you have far too many things to do, but if / when you get around to tweaking documentation, please take these points into consideration! 

Thanks for all your hard work
Will

**Comment by rob-p** [comment]
Hi @wmacnair,

  I'd like to thank you for taking the time to both appreciate the effort that has already been put into building an `alevin-fry` ecosystem while also providing detailed and constructive feedback on how to improve it!  This is exactly the type of feedback we hope to receive from the community.

  Given the nature of this feedback / request, I would like to move it over to a GitHub discussion, which should hopefully provide a better form for nuanced back and forth.  Further, since documentation is never really "complete", I'd feel bad closing this issue even if we got to making all of the suggested changes above (or doing something equivalent).  I will move this issue over to the "Discussions" section of the repo, and tag you (and the other maintainers there).  Hopefully, then we can have a more in-depth discussion about what you think the highest priority points to address are, as well as some of the other design decisions (e.g. there are some arguments for `fishpond` being the one-stop-shop for salmon/alevin related ingestion into R, though the lack of an equivalent package in python does cause some asymmetry between the R and Python ecosystems — e.g. `pyroe` must take on more responsibilities).

Thanks!
Rob
