### ISSUE TITLE
Error when running `./simpleaf index`: dependency ‘fishpond’ is not available

### ISSUE THREAD

**Issue by naity2** [COMBINE-lab/alevin-fry#58]
Dear Authors,

Thank you for providing this wonderful tool.

I'm have an issue when running `./simpleaf index`, which complains that the dependency ‘fishpond’ is not available. It looks like the `fishpond` package was left out the `/usefulaf/R/build_splici_ref.R` script.

Could you please help look into this?

Thanks very much!

```
Command error:                                                               
  Downloading GitHub repo COMBINE-lab/roe@HEAD
  Skipping 11 packages not available: SingleCellExperiment, fishpond, S4Vectors, GenomicRanges, GenomicFeatures, GenomeInfoDb, eisaR, BSgenome, Biostring
s, BiocGenerics, Biobase
  ERROR: dependency ‘fishpond’ is not available for package ‘roe’
  * removing ‘/opt/conda/lib/R/library/roe’
  Warning message:
  In i.p(...) :
    installation of package ‘/tmp/RtmpaVg9Dn/file1d18af58bf/roe_0.2.1.tar.gz’ had non-zero exit status
  Error in library(roe) : there is no package called ‘roe’
  Calls: suppressPackageStartupMessages -> withCallingHandlers -> library
  Execution halted
```

**Comment by rob-p** [comment]
Cc @DongzeHE

**Comment by DongzeHE** [comment]
Hello @naity2,

Thanks so much for bringing this issue to us. This bug is caused by the recent update of `roe`. I just updated the `usefulaf` repo to automatically detect and install `fishpond` into R environment if it doesn't exist. 

You can either open R and run `BiocManager::install(c("fishpond"))` and then continue to use your current version of `usefulaf`, or pull and run the latest version of `usefulaf`. 

I am sorry for the inconvenience.

-Dongze
