### ISSUE TITLE
processing trimmed or un-trimmed reads with alevin-fry 

### ISSUE THREAD

**Issue by Aintzane99** [COMBINE-lab/alevin-fry#70]
Hello, 

I would like to know if trimming the reads (removing the adaptor and low quality bases/reads) previous to mapping with alevin-fry makes a difference or not, since I wasn't able to find any mention of this in the tutorials. Does alevin-fry run some sort of trimming implemented in the mapping algorithm previous to aligning the reads or do you consider that it is not necessary? 

Thanks in advance,

Aintzane

**Comment by rob-p** [comment]
Hi @Aintzane99,

  Great question! We do not run any trimming algorithm during mapping, and I anticipate that the difference that trimming makes will depend somewhat on the mapping mode you use.  If you run `salmon alevin` with just the `--rad` flag, then selective-alignment is used.  Here, if there is adapter contamination, or a preponderance of low quality bases, they will detract from the alignment score and could adversely affect the mapping rate.  On the other hand, if you are using the `--sketch` flag, then the reads will be mapped using pseudoalignment with structural constraints.  Here, non-matching bases at the read ends won't detract from the mapping score, because alignment scoring isn't performed.  It's possible that a contaminated k-mer could erroneously map somewhere else in the index and prevent a read from mapping, but I'd expect such occurrences to be quite rare.  In the former case, it would be interesting to look at if (and where) it makes a difference.

Best,
Rob
