### ISSUE TITLE
no spike-in data in the gene-by-cell count matrices after UMI quantification

### ISSUE THREAD

**Issue by Aintzane99** [COMBINE-lab/alevin-fry#73]
Hello, 

I am working with data that has spike-ins and processing it in USA mode. I noticed that after generating the transcript-to-gene file by means of the provided code from the tutorial 'Resolving the splicing origins of UMIs to improve the specificity of single-cell RNA-seq transcriptome mapping with alevin-fry', the ' transcriptome_splici_fl71_t2g_3col.tsv' file did not contain the proper gene ID annotation for the spike in data:
![image](https://user-images.githubusercontent.com/92913155/175324180-465487e1-c682-4d67-b04e-29b6de7c9c2a.png)

Interestingly, the ' transcriptome_splici_fl71_t2g.tsv' had the correct annotation:
![image](https://user-images.githubusercontent.com/92913155/175324449-5be533b5-1e9d-4968-afd2-a9845ce66a08.png)

As a result, after the UMI quantification step (where I provided the 3 column file since I am using the USA mode), the matrices I obteined did not have spike-in data. I think the issue might have been in the '-' that the spike-ins have in their name, since Alevin-fry was able to detect the rest of the regular endogenous genes that have no '-' without any problems. 

Although I was able to manually fix the  'transcriptome_splici_fl71_t2g_3col.tsv' file, I just wanted to report the issue in case you wanted to consider it for later releases. 

Thanks you¡

Aintzane

**Comment by DongzeHE** [comment]
Haha, this is an interesting bug. I will fix this and generalize the code. Thanks so much @Aintzane99 for reporting this!

- Dongze

**Comment by DongzeHE** [comment]
Hello @Aintzane99,

The bug is fixed! You can downloaded the latest version of roe (v0.3.1)  from its github repo. Actually, there is a TODO tag hanging on that line of code saying that we should fix this bug but I ignored it all the time.

BTW, you don't need to concatenate the files by yourself because there is an`extra_spliced` parameter, of course, `extra_unspliced` as well ;), in the `make_splici_txome` function, which takes a string of the path to an extra FASTA file that you want to append to the splici transcriptome. In your case, you just need to say something like

```R
library(roe)
make_splici_txome(genome_path = "PATH_TO_THE_GENOME", 
                                  gtf_path = "PATH_TO_THE_GTF",
                                  read_length = READ_LENGTH,
                                  output_dir = "OUTPUT_DIR",
                                  extra_spliced = "ERCC92.fa")
```

The only caveat here is that by doing so, both the transcript ID and gene ID of the extra sequences in the output `t2g_3col.tsv` file will become their header in the `ERCC92.fa`. In your case, they will be

```
...
ERCC-00165	ERCC-00165	S
ERCC-00168	ERCC-00168	S
ERCC-00170	ERCC-00170	S
ERCC-00171	ERCC-00171	S
```

If the "transcript_id " section in the `ERCC92.gtf` file is important for your analysis, please feel free to ignore this suggestion.

Dongze

**Comment by rob-p** [comment]
Thanks, @DongzeHE!  Should we fix pyroe as well? Does it have the same bug?

**Comment by rob-p** [comment]
As it seems that `pyroe` didn't have this issue and @DongzeHE has (quickly!) fixed the issue in `roe`, I'm going to go ahead an close this issue for now.

**Comment by DongzeHE** [comment]
Last words: If you want to use `pyroe make-splici` + concatenated FASTA and GTF file, you have to remove the semicolon at the end of each line in the `ERCC92.gtf` because it will confuse the GTF reader that `pyroe` relies on. Or, as I said before, you can specify `--extra-spliced ERCC92.fa` and use the human genome and GTF file as the input.

Dongze
