### ISSUE TITLE
cargo failed to parse manifest at Cargo.toml

### ISSUE THREAD

**Issue by smoretti** [COMBINE-lab/alevin-fry#77]
Hi

I try to install alevin-fry version 0.6.0 with Rust 1.52.1 but the installation fails:
```
$ cargo install --path .
error: failed to parse manifest at `.../Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest
```

It works if I add `cargo-features = ["edition2021"]` at the top of the Cargo.toml file.

**Comment by rob-p** [comment]
Thanks for the issue!  I think this happens because the upgrade to the 2021 edition happened after development and testing switched over to 1.56.0, so that the annotation was no longer needed.  I suppose that adding this to the Cargo.toml file will allow use of the relevant features in earlier versions of rust as well, without affecting newer versions? As I mentioned in the other issue, we'll have to determine (in terms of features used) what the MSRV actually is here.
