### ISSUE TITLE
Cannot update libradicl

### ISSUE THREAD

**Issue by smoretti** [COMBINE-lab/alevin-fry#78]
I try to install alevin-fry version 0.6.0 with Rust 1.52.1 but the installation fails:
```
$ cargo install --path .
  Installing alevin-fry v0.6.0 (/var/vhosts/vitsoft-home/sib-easyconfigs.git/easybuild/easyconfigs/a/alevin-fry/alevin-fry-0.6.0)
    Updating crates.io index
    Updating git repository `https://github.com/COMBINE-lab/libradicl`
error: failed to compile `alevin-fry v0.6.0 (/var/vhosts/vitsoft-home/sib-easyconfigs.git/easybuild/easyconfigs/a/alevin-fry/alevin-fry-0.6.0)`, intermediate artifacts can be found at `/var/vhosts/vitsoft-home/sib-easyconfigs.git/easybuild/easyconfigs/a/alevin-fry/alevin-fry-0.6.0/target`

Caused by:
  failed to get `libradicl` as a dependency of package `alevin-fry v0.6.0 (/var/vhosts/vitsoft-home/sib-easyconfigs.git/easybuild/easyconfigs/a/alevin-fry/alevin-fry-0.6.0)`

Caused by:
  failed to load source for dependency `libradicl`

Caused by:
  Unable to update https://github.com/COMBINE-lab/libradicl

Caused by:
  failed to find branch `master`

Caused by:
  cannot locate remote-tracking branch 'origin/master'; class=Reference (4); code=NotFound (-3)
```

I think it comes from the `master` branch of libradicl that have been renamed `main`.

**Comment by rob-p** [comment]
Indeed; I think this is also due to an older version of rust being used (I should do an audit to determine what the MSRV is for a clean build).  It seems that this bug in cargo (assuming "master" for the main branch name) was [fixed in 1.55](https://github.com/rust-lang/cargo/pull/8522).  I'm happy to support older Rust versions if there are no fundamentally newer features being used, but development and CI are usually done on the latest _stable_ rust, which is why these issues didn't show up there.

On rust < 1.55, perhaps the fix is to either pull 0.4.6 directly (it's on crates.io) or to update  

https://github.com/COMBINE-lab/alevin-fry/blob/master/Cargo.toml#L41

to

```
libradicl = { git = "https://github.com/COMBINE-lab/libradicl",  branch = "main", version = "0.4.6" }
```

Thanks!
Rob

**Comment by smoretti** [comment]
Your fix `libradicl = { git = "https://github.com/COMBINE-lab/libradicl",  branch = "main", version = "0.4.6" }` works but then libradicl requires also `cargo-features = ["edition2021"]` #77 

So I now use Rust 1.60.0 and the installation works well

**Comment by rob-p** [comment]
Thanks for the update!  I'll be sure to add these constraints when we refresh the documentation on the next (patch) release.
